class Solution {
    public int numJewelsInStones(String jewels, String stones) {
        HashSet<Character> set = new HashSet<>();
        
        int n = jewels.length();
        
        for(int i=0;i<n;i++)
        {
            set.add(jewels.charAt(i));
        }
        
        n = stones.length();
        
        int ans = 0;
        
        for(int i=0;i<n;i++)
        {
            if(set.contains(stones.charAt(i)))
                ans++;
        }
        
        return ans;
    }
}
